#!/usr/bin/env python3
"""
Generate sps_preset_table.h from extracted GTA IV .sps shader preset files.

Parses all .sps files in the game's common/shaders/db/ directory and produces
a C++ header with a static table of SPS preset entries. This table is used at
runtime to populate the RAGE shader database (guest address 0x83127DAC) without
needing file I/O from guest code.

Usage:
    python3 generate_sps_table.py <sps_directory> [output_file]

Example:
    python3 generate_sps_table.py \
        "$HOME/Library/Application Support/LibertyRecomp/game/common/shaders/db" \
        ../LibertyRecomp/gpu/sps_preset_table.h
"""

import os
import sys
import re
from pathlib import Path


def parse_sps_file(filepath: Path) -> dict:
    """Parse a single .sps file and return its data."""
    result = {
        "sps_name": filepath.stem,  # e.g. "gta_vehicle_paint1"
        "fxc_name": None,
        "draw_bucket": 0,  # default opaque
        "params": [],  # list of (name, type, value)
    }

    with open(filepath, "r") as f:
        content = f.read().strip()

    if not content:
        return result

    lines = content.split("\n")
    i = 0
    while i < len(lines):
        line = lines[i].strip()

        # Parse "shader <name>"
        if line.startswith("shader "):
            result["fxc_name"] = line.split()[1].strip()
            i += 1
            continue

        # Parse parameter blocks: "name {\n\ttype value\n}"
        if line and not line.startswith("}") and not line.startswith("{"):
            param_name = line.rstrip(" {")
            if param_name and i + 1 < len(lines):
                # Look for opening brace on same line or next
                if "{" in line:
                    # Read type+value on next line
                    i += 1
                    if i < len(lines):
                        value_line = lines[i].strip()
                        parts = value_line.split(None, 1)
                        if len(parts) == 2:
                            ptype, pval = parts[0], parts[1]
                            if param_name == "__rage_drawbucket":
                                try:
                                    result["draw_bucket"] = int(pval)
                                except ValueError:
                                    pass
                            else:
                                result["params"].append(
                                    (param_name, ptype, pval)
                                )
                    # Skip closing brace
                    i += 1
                    if i < len(lines) and lines[i].strip() == "}":
                        i += 1
                    continue

        i += 1

    return result


def generate_header(entries: list, output_path: Path):
    """Generate the C++ header file with the SPS preset table."""

    # Sort entries by sps_name for deterministic output and binary search
    entries.sort(key=lambda e: e["sps_name"])

    with open(output_path, "w") as f:
        f.write("// Auto-generated by tools/generate_sps_table.py\n")
        f.write("// Do not edit manually.\n")
        f.write("#pragma once\n\n")
        f.write("#include <cstdint>\n")
        f.write("#include <cstddef>\n\n")

        # Parameter entry struct
        f.write("struct SpsParamEntry {\n")
        f.write("    const char* name;\n")
        f.write("    float value;\n")
        f.write("};\n\n")

        # SPS preset entry struct
        f.write("struct SpsPresetEntry {\n")
        f.write("    const char* spsName;       // e.g. \"gta_vehicle_paint1\"\n")
        f.write("    const char* fxcName;       // e.g. \"gta_vehicle_paint1\" (the shader keyword value)\n")
        f.write("    uint8_t drawBucket;        // __rage_drawbucket value (0=default opaque)\n")
        f.write("    uint8_t paramCount;        // number of float parameters\n")
        f.write("    const SpsParamEntry* params; // pointer to parameter array (or nullptr)\n")
        f.write("};\n\n")

        # Generate parameter arrays for entries that have params
        param_arrays = {}
        for entry in entries:
            if entry["params"]:
                array_name = f"s_spsParams_{entry['sps_name']}"
                param_arrays[entry["sps_name"]] = array_name
                f.write(f"static const SpsParamEntry {array_name}[] = {{\n")
                for pname, ptype, pval in entry["params"]:
                    # Convert to float
                    try:
                        fval = float(pval)
                    except ValueError:
                        fval = 0.0
                    f.write(f'    {{ "{pname}", {fval}f }},\n')
                f.write("};\n\n")

        # Generate the main table
        # NOTE: spsName MUST include ".sps" extension — the original game's
        # directory scanner (sub_82869D08) stores filenames WITH extension in
        # entry+8, and the model data at material+68 also uses the extension
        # for the strcmp lookup in sub_82869FC0.
        f.write(f"static const SpsPresetEntry g_spsPresetTable[] = {{\n")
        for entry in entries:
            sps = entry["sps_name"] + ".sps"  # Include extension for DB match
            fxc = entry["fxc_name"] or entry["sps_name"]
            bucket = entry["draw_bucket"]
            pcount = len(entry["params"])
            parray = param_arrays.get(entry["sps_name"], "nullptr")
            f.write(f'    {{ "{sps}", "{fxc}", {bucket}, {pcount}, {parray} }},\n')
        f.write("};\n\n")

        f.write(
            f"static const size_t g_spsPresetTableCount = {len(entries)};\n"
        )

    print(f"Generated {output_path} with {len(entries)} SPS entries")

    # Print summary
    fxc_set = set(e["fxc_name"] for e in entries if e["fxc_name"])
    bucket_counts = {}
    for e in entries:
        b = e["draw_bucket"]
        bucket_counts[b] = bucket_counts.get(b, 0) + 1
    param_count = sum(1 for e in entries if e["params"])

    print(f"  {len(fxc_set)} unique FXC references")
    print(f"  {param_count} entries with parameters")
    print(f"  Draw bucket distribution: {dict(sorted(bucket_counts.items()))}")


def main():
    if len(sys.argv) < 2:
        # Default path for macOS
        sps_dir = os.path.expanduser(
            "~/Library/Application Support/LibertyRecomp/game/common/shaders/db"
        )
    else:
        sps_dir = sys.argv[1]

    if len(sys.argv) >= 3:
        output_path = Path(sys.argv[2])
    else:
        output_path = Path(__file__).parent.parent / "LibertyRecomp" / "gpu" / "sps_preset_table.h"

    sps_dir = Path(sps_dir)
    if not sps_dir.exists():
        print(f"Error: SPS directory not found: {sps_dir}")
        sys.exit(1)

    sps_files = sorted(sps_dir.glob("*.sps"))
    if not sps_files:
        print(f"Error: No .sps files found in {sps_dir}")
        sys.exit(1)

    print(f"Parsing {len(sps_files)} .sps files from {sps_dir}")

    entries = []
    for sps_file in sps_files:
        entry = parse_sps_file(sps_file)
        if entry["fxc_name"]:
            entries.append(entry)
        else:
            print(f"  Warning: {sps_file.name} has no 'shader' line, skipping")

    generate_header(entries, output_path)


if __name__ == "__main__":
    main()
